/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/problems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every top-level error code
         * @description The closed registry of top-level error codes. Unauthenticated. Sorted by domain, then code.
         */
        get: operations["listProblemTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/problems/reasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every field-level error reason
         * @description The closed registry of field-level reasons. Unauthenticated. Values in this list never appear as top-level codes.
         */
        get: operations["listProblemReasons"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List topics
         * @description Lists topics visible to the caller as a cursor page. Anonymous callers see public published topics. Signed-in callers also see login-scoped topics. Role and user grants never appear. Hidden topics never appear. Topics by banned authors are left out; the server reads on to fill the page, so every page but the last holds limit items unless a long run of such topics cuts it short. Continue while next_cursor is present, whatever the page size.
         */
        get: operations["listTopics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A block node. Switch on object; render an unknown type's children, or its value as text. */
        BlockNode: components["schemas"]["ParagraphNode"] | components["schemas"]["HeadingNode"] | components["schemas"]["ThematicBreakNode"] | components["schemas"]["BlockquoteNode"] | components["schemas"]["ListNode"] | components["schemas"]["CodeNode"] | components["schemas"]["MathNode"] | components["schemas"]["TableNode"] | components["schemas"]["SpoilerNode"];
        BlockquoteNode: {
            /** @description Quoted block nodes. */
            children: components["schemas"]["BlockNode"][];
            /**
             * @description Type discriminant. Always blockquote. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            object: "blockquote";
        };
        BreakNode: {
            /**
             * @description Type discriminant. Always break. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            object: "break";
        };
        CodeNode: {
            /** @description Language named on the fence, lowercased. null when the fence names none or the block is indented. */
            lang: string | null;
            /**
             * @description Type discriminant. Always code. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            object: "code";
            /** @description Source text of the block, without the fences. Free text; never use it as a decision input. */
            value: string;
        };
        ContentDocument: {
            /** @description Top-level block nodes in document order. Empty array for an empty body. */
            children: components["schemas"]["BlockNode"][];
            /**
             * @description Type discriminant. Always document.
             * @enum {string}
             */
            object: "document";
        };
        EmphasisNode: {
            /** @description Emphasized inline nodes. */
            children: components["schemas"]["InlineNode"][];
            /**
             * @description Type discriminant. Always emphasis. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            object: "emphasis";
        };
        FieldError: {
            /** @description English diagnostic for this location. Free text; never use it as a decision input. */
            detail: string;
            /** @description Header name. Exactly one of pointer, parameter, or header is present. */
            header?: string;
            /** @description Query or path parameter name. Exactly one of pointer, parameter, or header is present. */
            parameter?: string;
            /** @description Reason-specific bounds or allowed values. Omitted when the reason has no params. */
            params?: components["schemas"]["FieldParams"];
            /** @description JSON Pointer to a body location. Exactly one of pointer, parameter, or header is present. */
            pointer?: string;
            /** @description Field-level reason. UPPER_SNAKE. Disjoint from top-level codes. */
            reason: string;
        };
        FieldParams: {
            /** @description Closed vocabulary members that were expected. */
            allowed?: string[];
            /**
             * Format: int64
             * @description Maximum array length the value exceeded.
             */
            max_items?: number;
            /**
             * Format: int64
             * @description Maximum string length the value exceeded.
             */
            max_length?: number;
            /**
             * Format: double
             * @description Inclusive numeric upper bound the value missed.
             */
            maximum?: number;
            /**
             * Format: int64
             * @description Minimum array length the value failed.
             */
            min_items?: number;
            /**
             * Format: int64
             * @description Minimum string length the value failed.
             */
            min_length?: number;
            /**
             * Format: double
             * @description Inclusive numeric lower bound the value missed.
             */
            minimum?: number;
        };
        HeadingNode: {
            /** @description Fragment identifier of this heading, unique within the document. Links in the same body point at it as #anchor. */
            anchor: string;
            /** @description Inline nodes of the heading text. */
            children: components["schemas"]["InlineNode"][];
            /**
             * Format: int64
             * @description Heading level, 2 to 6. The page title is the only level 1, so a level-1 heading in the source arrives as 2.
             */
            depth: number;
            /**
             * @description Type discriminant. Always heading. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            object: "heading";
        };
        Image: {
            /** @description Image-service content hash. */
            hash: string;
            /**
             * Format: int64
             * @description Pixel height. null if unknown.
             */
            height: number | null;
            /**
             * @description Sexual depiction: safe, suggestive, or explicit. null means not assessed.
             * @enum {string|null}
             */
            sexual: "safe" | "suggestive" | "explicit" | null;
            /** @description Thumbhash. null if unknown. */
            thumbhash: string | null;
            /**
             * Format: uri
             * @description Absolute image URL. Never a bare hash.
             */
            url: string;
            /**
             * Format: int64
             * @description Pixel width. null if unknown.
             */
            width: number | null;
        };
        ImageNode: {
            /** @description Alternative text. Empty when the author gave none. Free text; never use it as a decision input. */
            alt: string;
            /** @description Image-service record of the picture, whose url is the full-size original. null for a picture hosted elsewhere. */
            image: components["schemas"]["Image"] | null;
            /**
             * @description Type discriminant. Always image. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            object: "image";
            /**
             * Format: uri
             * @description Absolute URL to display inline. For an image-service picture it may be a smaller variant of image.url.
             */
            url: string;
        };
        InlineCodeNode: {
            /**
             * @description Type discriminant. Always inline_code. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            object: "inline_code";
            /** @description Code text. Free text; never use it as a decision input. */
            value: string;
        };
        InlineMathNode: {
            /**
             * @description Type discriminant. Always inline_math. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            object: "inline_math";
            /** @description TeX source of an inline formula, without the delimiters. Free text; never use it as a decision input. */
            value: string;
        };
        /** @description An inline node. Switch on object; render an unknown type's children, or its value as text. */
        InlineNode: components["schemas"]["TextNode"] | components["schemas"]["EmphasisNode"] | components["schemas"]["StrongNode"] | components["schemas"]["StrikethroughNode"] | components["schemas"]["InlineCodeNode"] | components["schemas"]["InlineMathNode"] | components["schemas"]["BreakNode"] | components["schemas"]["LinkNode"] | components["schemas"]["ImageNode"] | components["schemas"]["VideoNode"] | components["schemas"]["InlineSpoilerNode"] | components["schemas"]["MentionNode"] | components["schemas"]["ReplyReferenceNode"];
        InlineSpoilerNode: {
            /** @description Inline nodes hidden until the reader reveals them. */
            children: components["schemas"]["InlineNode"][];
            /**
             * @description Type discriminant. Always inline_spoiler. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            object: "inline_spoiler";
        };
        LinkNode: {
            /** @description Inline nodes of the link text. */
            children: components["schemas"]["InlineNode"][];
            /**
             * @description Type discriminant. Always link. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            object: "link";
            /**
             * Format: uri
             * @description Absolute http, https or mailto URL.
             */
            url: string;
        };
        ListItemNode: {
            /** @description Block nodes of the item. */
            children: components["schemas"]["BlockNode"][];
            /** @description Task-list state: true when ticked, false when not. null when the item is not a task. */
            is_checked: boolean | null;
            /**
             * @description Type discriminant. Always list_item.
             * @enum {string}
             */
            object: "list_item";
        };
        ListNode: {
            /** @description Items of the list. */
            children: components["schemas"]["ListItemNode"][];
            /** @description Whether the items are numbered. */
            is_ordered: boolean;
            /** @description Whether the source separates items with blank lines, which renders them with paragraph spacing. */
            is_spread: boolean;
            /**
             * @description Type discriminant. Always list. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            object: "list";
            /**
             * Format: int64
             * @description Number of the first item of an ordered list. null for an unordered list.
             */
            start: number | null;
        };
        ListProblemReason: {
            /** @description Members of this page. Empty array, never null. */
            items: components["schemas"]["ProblemReason"][];
            /** @description Opaque keyset cursor. Omitted on the last page. */
            next_cursor?: string;
            /**
             * @description Type discriminant. Always list.
             * @enum {string}
             */
            object: "list";
        };
        ListProblemType: {
            /** @description Members of this page. Empty array, never null. */
            items: components["schemas"]["ProblemType"][];
            /** @description Opaque keyset cursor. Omitted on the last page. */
            next_cursor?: string;
            /**
             * @description Type discriminant. Always list.
             * @enum {string}
             */
            object: "list";
        };
        ListTopicSummary: {
            /** @description Members of this page. Empty array, never null. */
            items: components["schemas"]["TopicSummary"][];
            /** @description Opaque keyset cursor. Omitted on the last page. */
            next_cursor?: string;
            /**
             * @description Type discriminant. Always list.
             * @enum {string}
             */
            object: "list";
        };
        MathNode: {
            /**
             * @description Type discriminant. Always math. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            object: "math";
            /** @description TeX source of a display formula, without the delimiters. Free text; never use it as a decision input. */
            value: string;
        };
        MentionNode: {
            /** @description The user mentioned, with the current display name. Render it as @name. */
            mentioned_user: components["schemas"]["UserRef"];
            /**
             * @description Type discriminant. Always mention. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            object: "mention";
        };
        ParagraphNode: {
            /** @description Inline nodes of the paragraph. Empty array for a blank line the author kept. */
            children: components["schemas"]["InlineNode"][];
            /**
             * @description Type discriminant. Always paragraph. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            object: "paragraph";
        };
        Problem: {
            /** @description Top-level error code. UPPER_SNAKE. */
            code: string;
            /** @description English diagnostic for this request. Free text; never use it as a decision input. */
            detail: string;
            /** @description Field-level errors. Empty array, never null. */
            errors: components["schemas"]["FieldError"][];
            /** @description Request path and query that failed. */
            instance: string;
            /** @description Request correlation id. Echoed from X-Request-ID when valid. */
            request_id: string;
            /**
             * Format: int64
             * @description HTTP status this code is bound to. One status per code.
             */
            status: number;
            /** @description Stable English phrase for this type. Does not vary per request. */
            title: string;
            /**
             * Format: uri
             * @description Problem type URI. The last path segment is the kebab-case form of code.
             */
            type: string;
        };
        ProblemReason: {
            /** @description English prose. Free text; never use it as a decision input. */
            description: string;
            /**
             * @description Type discriminant. Always problem_reason.
             * @enum {string}
             */
            object: "problem_reason";
            /** @description Keys this reason can carry in a field error's params. Empty array when it carries none. */
            param_names: string[];
            /** @description Field-level reason. UPPER_SNAKE. Disjoint from top-level codes. */
            reason: string;
            /** @description Stable English phrase for this reason. */
            title: string;
        };
        ProblemType: {
            /** @description Top-level error code. UPPER_SNAKE. */
            code: string;
            /** @description English prose. Free text; never use it as a decision input. */
            description: string;
            /**
             * @description Type URI domain segment.
             * @enum {string}
             */
            domain: "platform" | "kungal";
            /**
             * @description Type discriminant. Always problem_type.
             * @enum {string}
             */
            object: "problem_type";
            /**
             * Format: int64
             * @description HTTP status this code is bound to. One status per code.
             */
            status: number;
            /** @description Stable English phrase for this type. Does not vary per request. */
            title: string;
            /**
             * Format: uri
             * @description Problem type URI. The last path segment is the kebab-case form of code.
             */
            type: string;
        };
        ReplyReferenceNode: {
            /**
             * Format: int64
             * @description Floor number of the referenced reply as the author saw it. Render it as #floor.
             */
            floor: number;
            /**
             * @description Type discriminant. Always reply_reference. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            object: "reply_reference";
            /** @description Id of the referenced reply in the same topic. */
            reply_id: string;
        };
        SpoilerNode: {
            /** @description Block nodes hidden until the reader reveals them. */
            children: components["schemas"]["BlockNode"][];
            /**
             * @description Type discriminant. Always spoiler. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            object: "spoiler";
        };
        StrikethroughNode: {
            /** @description Struck-through inline nodes. */
            children: components["schemas"]["InlineNode"][];
            /**
             * @description Type discriminant. Always strikethrough. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            object: "strikethrough";
        };
        StrongNode: {
            /** @description Strongly emphasized inline nodes. */
            children: components["schemas"]["InlineNode"][];
            /**
             * @description Type discriminant. Always strong. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            object: "strong";
        };
        TableCellNode: {
            /**
             * @description Horizontal alignment of the column. null for the default.
             * @enum {string|null}
             */
            align: "left" | "center" | "right" | null;
            /** @description Inline nodes of the cell. */
            children: components["schemas"]["InlineNode"][];
            /**
             * @description Type discriminant. Always table_cell.
             * @enum {string}
             */
            object: "table_cell";
        };
        TableNode: {
            /** @description Rows of the table. The first row is the header row. */
            children: components["schemas"]["TableRowNode"][];
            /**
             * @description Type discriminant. Always table. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            object: "table";
        };
        TableRowNode: {
            /** @description Cells of the row, one per column. */
            children: components["schemas"]["TableCellNode"][];
            /**
             * @description Type discriminant. Always table_row.
             * @enum {string}
             */
            object: "table_row";
        };
        TextNode: {
            /**
             * @description Type discriminant. Always text. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            object: "text";
            /** @description Literal text. Escapes and entities are already decoded; render it as text, never as markup. Free text; never use it as a decision input. */
            value: string;
        };
        ThematicBreakNode: {
            /**
             * @description Type discriminant. Always thematic_break. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            object: "thematic_break";
        };
        TopicSummary: {
            /** @description Topic author. */
            author: components["schemas"]["UserRef"];
            /**
             * Format: date-time
             * @description Bump time. Replies, comments, poll votes and lottery events set it to now, but only for topics created within the last 3 months. It is not a last-activity time.
             */
            bumped_at: string;
            /**
             * @description Topic category.
             * @enum {string}
             */
            category: "galgame" | "technique" | "others";
            /**
             * Format: int64
             * @description Comment count.
             */
            comment_count: number;
            /** @description Cover images in stored token order. Tokens that do not parse are skipped. Empty array if none. */
            cover_images: components["schemas"]["Image"][];
            /**
             * Format: date-time
             * @description Creation time.
             */
            created_at: string;
            /** @description Whether a best-answer reply is set. */
            has_best_answer: boolean;
            /** @description Topic id. JSON string of a decimal integer. */
            id: string;
            /** @description Whether the topic is marked NSFW. */
            is_nsfw: boolean;
            /**
             * Format: int64
             * @description Like count.
             */
            like_count: number;
            /** @description Mini-apps attached to the topic, in registry order. Empty array if none. */
            mini_apps: ("poll" | "lottery")[];
            /**
             * @description Type discriminant. Always topic.
             * @enum {string}
             */
            object: "topic";
            /**
             * Format: int64
             * @description Reply count.
             */
            reply_count: number;
            /** @description Section slugs, in stored order. Empty array if none. Hyphenated URL segments of /section/{key}. */
            sections: ("g-walkthrough" | "g-chatting" | "g-article" | "g-seeking" | "g-news" | "g-releases" | "g-other" | "t-crack" | "t-web" | "t-languages" | "t-help" | "t-linux" | "t-practical" | "t-ai" | "t-android" | "t-adobe" | "t-algorithm" | "t-other" | "o-anime" | "o-comics" | "o-music" | "o-novel" | "o-daily" | "o-essay" | "o-forum" | "o-patch" | "o-other")[];
            /**
             * @description Lifecycle state. A hidden topic is visible only to its author and to staff.
             * @enum {string}
             */
            state: "published" | "hidden";
            /** @description Topic title as stored. Free text; never use it as a decision input. */
            title: string;
            /**
             * Format: date-time
             * @description Time of the latest upvote. null when the topic has never been upvoted.
             */
            upvoted_at: string | null;
            /**
             * Format: int64
             * @description Lifetime view count.
             */
            view_count: number;
        };
        UserRef: {
            /** @description Avatar image. null when the account has no image-service hash. */
            avatar: components["schemas"]["Image"] | null;
            /** @description User id. JSON string of a decimal integer. */
            id: string;
            /** @description Display name. null when the account no longer exists; show a localized label. Free text; never use it as a decision input. */
            name: string | null;
            /**
             * @description Type discriminant. Always user.
             * @enum {string}
             */
            object: "user";
        };
        VideoNode: {
            /**
             * @description Type discriminant. Always video. (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            object: "video";
            /**
             * Format: uri
             * @description Absolute URL of the video file.
             */
            url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProblemTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListProblemType"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listProblemReasons: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListProblemReason"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listTopics: {
        parameters: {
            query?: {
                /** @description Opaque keyset cursor from a previous page of this collection. */
                cursor?: string;
                /** @description Page size. 1–100, default 20. Values above 100 are rejected, not clamped. */
                limit?: number;
                /** @description Sort order; ties break on id in the same direction. Default bumped_desc. bumped: bumped_at. created: created_at. views: view_count. views_1d: views today. views_7d and views_30d: views in the last 7 or 30 days, recomputed daily. likes: like_count. favorites: times favorited. upvotes: times upvoted. */
                sort?: "bumped_asc" | "bumped_desc" | "created_asc" | "created_desc" | "views_asc" | "views_desc" | "views_1d_asc" | "views_1d_desc" | "views_7d_asc" | "views_7d_desc" | "views_30d_asc" | "views_30d_desc" | "likes_asc" | "likes_desc" | "favorites_asc" | "favorites_desc" | "upvotes_asc" | "upvotes_desc";
                /** @description When set, only this category. Omitted means every category. There is no all token. */
                category?: "galgame" | "technique" | "others";
                /** @description When true, NSFW topics are included. Default false. */
                include_nsfw?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListTopicSummary"];
                };
            };
            /** @description INVALID_PARAMETER, LIMIT_TOO_LARGE, UNKNOWN_SORT, UNKNOWN_ENUM_VALUE, or INVALID_CURSOR. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
