import type { components } from '../../types/api/v1'

export type Image = components['schemas']['Image']
export type TopicSummary = components['schemas']['TopicSummary']
export type Topic = components['schemas']['Topic']
export type TopicViewer = components['schemas']['TopicViewer']
export type Reply = components['schemas']['Reply']
export type ReplyViewer = components['schemas']['ReplyViewer']
export type Comment = components['schemas']['Comment']
export type CommentViewer = components['schemas']['CommentViewer']
export type ReactionSummary = components['schemas']['ReactionSummary']
export type ListReply = components['schemas']['ListReply']
export type UserRef = components['schemas']['UserRef']
export type ListMoyuPatch = components['schemas']['ListMoyuPatch']
export type MoyuPatchResource = components['schemas']['MoyuPatchResource']

export type ContentDocument = components['schemas']['ContentDocument']
export type BlockNode = components['schemas']['BlockNode']
export type InlineNode = components['schemas']['InlineNode']
export type ListItemNode = components['schemas']['ListItemNode']
export type ListNode = components['schemas']['ListNode']
export type TableRowNode = components['schemas']['TableRowNode']
export type TableCellNode = components['schemas']['TableCellNode']
export type TableNode = components['schemas']['TableNode']
export type ParagraphNode = components['schemas']['ParagraphNode']
export type HeadingNode = components['schemas']['HeadingNode']
export type CodeNode = components['schemas']['CodeNode']
export type ImageNode = components['schemas']['ImageNode']
export type LinkNode = components['schemas']['LinkNode']
export type MentionNode = components['schemas']['MentionNode']
export type ReplyReferenceNode = components['schemas']['ReplyReferenceNode']
export type VideoNode = components['schemas']['VideoNode']
