import type { components } from '../../types/api/v1'

export type Image = components['schemas']['Image']
export type TopicSummary = components['schemas']['TopicSummary']
export type UserRef = components['schemas']['UserRef']

export type ContentDocument = components['schemas']['ContentDocument']
export type BlockNode = components['schemas']['BlockNode']
export type InlineNode = components['schemas']['InlineNode']
export type ListItemNode = components['schemas']['ListItemNode']
export type ListNode = components['schemas']['ListNode']
export type TableRowNode = components['schemas']['TableRowNode']
export type TableCellNode = components['schemas']['TableCellNode']
export type TableNode = components['schemas']['TableNode']
export type ParagraphNode = components['schemas']['ParagraphNode']
export type HeadingNode = components['schemas']['HeadingNode']
export type CodeNode = components['schemas']['CodeNode']
export type ImageNode = components['schemas']['ImageNode']
export type LinkNode = components['schemas']['LinkNode']
export type MentionNode = components['schemas']['MentionNode']
export type ReplyReferenceNode = components['schemas']['ReplyReferenceNode']
export type VideoNode = components['schemas']['VideoNode']
